name: local-tests

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    container:
      image: alpine:3.14

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: |
          mkdir -p $GITHUB_WORKSPACE/out
          echo "Hello, world!" > $GITHUB_WORKSPACE/out/db_fuzzer.log
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: db_fuzzer_log
          path: ${{ github.workspace }}/out/db_fuzzer.log
          
          
  download:
    needs: [upload]
    runs-on: ubuntu-latest
    container:
      image: alpine:3.14

    steps:
    
      - name: pre
        run: |
          mkdir -p $GITHUB_WORKSPACE/out
      
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: db_fuzzer_log
          path: |
            ${{ github.workspace }}/out/db_fuzzer.log
      
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: |
          ls -alFh $GITHUB_WORKSPACE
          ls -alFh $GITHUB_WORKSPACE/out
