name: local-tests

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    container:
      image: alpine:3.14

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: |
          if [ 0 == 0 ]; then
            return 0
          fi
