name: New Release Line

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: alpine:3.14

    steps:
      - uses: actions/checkout@v3

      - name: Calculate tag
        run: |
          major=$(cat $GITHUB_WORKSPACE/include/rocksdb/version.h | grep '#define ROCKSDB_MAJOR' | grep -o '[^,]\+$' | tr ' ' '\n' | tail -n1)
          minor=$(cat $GITHUB_WORKSPACE/include/rocksdb/version.h | grep '#define ROCKSDB_MINOR' | grep -o '[^,]\+$' | tr ' ' '\n' | tail -n1)
          minor=$(echo $minor + 1 | bc)
          echo $minor
          echo "major=$major" >> $GITHUB_ENV
          echo "minor=$minor" >> $GITHUB_ENV
          current_version="$major.$minor.dev"
          echo $current_version

      - name: Update version.h
        run: |
          sed -i -e 's/#define ROCKSDB_MAJOR.*/#define ROCKSDB_MAJOR ${{ env.major }}/' include/rocksdb/version.h
          sed -i -e 's/#define ROCKSDB_MINOR.*/#define ROCKSDB_MINOR ${{ env.minor }}/' include/rocksdb/version.h
          cat include/rocksdb/version.h
          
      - name: Create release branch
        run: |
          new_branch="release/{{ env.major }}.{{ env.minor }}"
          echo $new_branch
          #git checkout -b 
