name: New Release Line

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: alpine:3.14

    steps:
      - uses: actions/checkout@v3

      - name: Calculate tag
        run: |
          major=$(cat $GITHUB_WORKSPACE/include/rocksdb/version.h | grep '#define ROCKSDB_MAJOR' | grep -o '[^,]\+$' | tr ' ' '\n' | tail -n1)
          minor=$(cat $GITHUB_WORKSPACE/include/rocksdb/version.h | grep '#define ROCKSDB_MINOR' | grep -o '[^,]\+$' | tr ' ' '\n' | tail -n1)
          minor=$(echo $minor + 1 | bc)
          echo $minor
          echo "major=$major" >> $GITHUB_ENV
          echo "minor=$minor" >> $GITHUB_ENV
          current_version="$major.$minor.dev"
          echo $current_version
          echo ${{ env.major }}
          echo ${{ env.minor }}
          sed -i -e 's/ROCKSDB_MAJOR.*/ROCKSDB_MAJOR ${{ env.major }}/' include/rocksdb/version.h
          sed -i -e 's/ROCKSDB_MINOR.*/ROCKSDB_MINOR ${{ env.minor }}/' include/rocksdb/version.h
          cat include/rocksdb/version.h

      - name: Create new release branch
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
