name: New Release Line

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:18.04

    steps:
      - uses: actions/checkout@v3

      - name: Calculate tag
        run: |
          major=$(cat $GITHUB_WORKSPACE/include/rocksdb/version.h | grep '#define ROCKSDB_MAJOR' | grep -o '[^,]\+$' | tr ' ' '\n' | tail -n1)
          minor=$(cat $GITHUB_WORKSPACE/include/rocksdb/version.h | grep '#define ROCKSDB_MINOR' | grep -o '[^,]\+$' | tr ' ' '\n' | tail -n1)
          cur_ver="$major.$minor.dev"
          echo $current_version

      - name: Create new release branch
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
