# This is a basic workflow to help you get started with Actions

name: random

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  upload:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: alpine:3.14

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          mkdir -p $GITHUB_WORKSPACE/out
          echo "Hello, world!" > $GITHUB_WORKSPACE/out/db_fuzzer.log
          

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: db_fuzzer_log
          path: ${{ github.workspace }}/out/db_fuzzer.log
          
          
  download:
    needs: [upload]
    runs-on: ubuntu-latest
    container:
      image: alpine:3.14

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: db_fuzzer_log
          path: |
            ${{ github.workspace }}/out/db_fuzzer.log
      
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          ls -alFh $GITHUB_WORKSPACE
          ls -alFh $GITHUB_WORKSPACE/out || echo skoot
          ls -alFh $GITHUB_WORKSPACE/out/db_fuzzer.log || echo skid
          
