name: Tests

on:

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: unit-test
            command: make -j16 check && echo $? || echo $?
          - mame: black box
            command: CRASH_TEST_EXT_ARGS="--duration=500" make -j16 blackbox_asan_crash_test && echo $? || echo $?
          - mame: white box
            command: CRASH_TEST_EXT_ARGS="--duration=500" make -j16 whitebox_asan_crash_test && echo $? || echo $?
    steps:
    
      - name: Pre
        run: sudo apt-get update -y && sudo apt-get install -y libgflags-dev
    
      - name: Checkout
        uses: actions/checkout@v3

      - name: ${{ matrix.name }}
        run: |
          echo "export GTEST_THROW_ON_FAILURE=0" >> $BASH_ENV
          echo "export GTEST_OUTPUT=\"xml:/tmp/test-results/\"" >> $BASH_ENV
          echo "export SKIP_FORMAT_BUCK_CHECKS=1" >> $BASH_ENV
          echo "export GTEST_COLOR=1" >> $BASH_ENV
          echo "export CTEST_OUTPUT_ON_FAILURE=1" >> $BASH_ENV
          echo "export CTEST_TEST_TIMEOUT=300" >> $BASH_ENV
          echo "export ZLIB_DOWNLOAD_BASE=https://rocksdb-deps.s3.us-west-2.amazonaws.com/pkgs/zlib" >> $BASH_ENV
          echo "export BZIP2_DOWNLOAD_BASE=https://rocksdb-deps.s3.us-west-2.amazonaws.com/pkgs/bzip2" >> $BASH_ENV
          echo "export SNAPPY_DOWNLOAD_BASE=https://rocksdb-deps.s3.us-west-2.amazonaws.com/pkgs/snappy" >> $BASH_ENV
          echo "export LZ4_DOWNLOAD_BASE=https://rocksdb-deps.s3.us-west-2.amazonaws.com/pkgs/lz4" >> $BASH_ENV
          echo "export ZSTD_DOWNLOAD_BASE=https://rocksdb-deps.s3.us-west-2.amazonaws.com/pkgs/zstd" >> $BASH_ENV
          ${{ matrix.command }}
        
# ####in progress####
#   fuzz-test:
#     uses: speedb-io/rocksdb/.github/workflows/fuzz-test@main
