name: test

on:

  workflow_dispatch:

jobs:
  call-workflow-passing-data:
    uses: nathan-bo/workflows/.github/workflows/ci-workflow.yml@main
    with:
      username: ${{ inputs.username }}
      token: ${{ secrets.token }}

