name: test

on:
  workflow_dispatch:

jobs:
  ci_workflow:
    uses: nathan-bo/workflows/.github/workflows/ci-workflow.yml@main
    with:
      username: ${{ secrets.username }}
      token: ${{ secrets.token }}
