name: test

on:

  workflow_dispatch:

jobs:
  call-workflow-passing-data:
    uses: nathan-bo/workflows/.github/workflows/ci-workflow.yml@main #octo-org/example-repo/.github/workflows/reusable-workflow.yml@main
    with:
      username: ${{ secrets.USERNAME }}
    secrets: inherit
